"""Fix 3 (docs/improve.md): tag/complements enrichment, keyed by full
sku_id. Applied on top of each SKU's own tuple-defined tags/complements in
seed_catalog.py's build_catalog() — kept as its own reviewable data block
rather than hand-editing all 120 tuples in SKUS_BY_CATEGORY in place.

Every SKU gets 5-7 tags including >=1 from the closed mission-tag
vocabulary (MISSION_TAGS, mirrored in backend/catalog.py — keep both
lists in sync if this ever changes) and 3-4 complements. complements
here are stored as full sku_ids (unlike the tuple field, which uses bare
slugs auto-prefixed by build_catalog()).

Satisfies every sanity pair in docs/improve.md Fix 3 except one honestly
left uncovered: "protein/health food -> shaker" has no reasonable
substitute anywhere in the 120-SKU catalog (checked all electronics and
home SKUs) — forcing a bad link would be worse than the gap. Three other
sanity-pair targets don't exist as SKUs either and were substituted with
the closest real fit: diaper rash cream -> baby powder, cleaning gloves
-> dishwash liquid, cotton pads -> hydrating sheet mask.
"""

MISSION_TAGS = {
    "breakfast", "lunch", "dinner", "late-night", "tea-coffee-time",
    "party", "festival", "guests", "gifting",
    "cleaning", "laundry", "kitchen-restock",
    "baby-care", "pet-care", "personal-care", "grooming",
    "wellness", "sleep", "immunity", "first-aid",
    "desk-setup", "travel", "monsoon", "summer",
}


def _c(*slugs: str) -> list[str]:
    return [f"sku_{s}" for s in slugs]


CATALOG_ENRICHMENT: dict[str, dict] = {
    # STAPLES
    "sku_atta_ww_01": {"tags": ["atta", "wheat", "flour", "staple", "chakki-fresh", "kitchen-restock", "breakfast"],
                        "complements": _c("toor_dal_01", "ghee_01", "besan_01")},
    "sku_maida_01": {"tags": ["maida", "refined-flour", "baking", "kitchen-restock", "dinner"],
                      "complements": _c("sugar_01", "besan_01", "butter_01")},
    "sku_rice_basmati_01": {"tags": ["rice", "basmati", "staple", "lunch", "dinner", "kitchen-restock"],
                             "complements": _c("toor_dal_01", "curd_01", "onion_01", "tomato_01")},
    "sku_toor_dal_01": {"tags": ["dal", "toor", "pulses", "protein", "wellness", "lunch", "kitchen-restock"],
                         "complements": _c("rice_basmati_01", "onion_01", "ghee_01")},
    "sku_moong_dal_01": {"tags": ["dal", "moong", "pulses", "protein", "wellness", "immunity", "lunch"],
                          "complements": _c("rice_basmati_01", "ghee_01", "onion_01")},
    "sku_sugar_01": {"tags": ["sugar", "sweetener", "kitchen-restock", "tea-coffee-time", "breakfast"],
                      "complements": _c("coffee_instant_01", "green_tea_01", "milk_01")},
    "sku_salt_01": {"tags": ["salt", "iodized", "kitchen-restock", "lunch", "dinner"],
                     "complements": _c("toor_dal_01", "rice_basmati_01", "tomato_01")},
    "sku_pasta_01": {"tags": ["italian", "dinner", "pasta", "durum-wheat", "guests"],
                      "complements": _c("pasta_sauce_01", "garlicbread_01", "parmesan_01", "garlic_pod_01")},
    "sku_pasta_sauce_01": {"tags": ["italian", "dinner", "pasta-complement", "sauce", "guests"],
                            "complements": _c("pasta_01", "garlicbread_01", "basil_bunch_01", "mushroom_01")},
    "sku_besan_01": {"tags": ["besan", "gram-flour", "staple", "kitchen-restock", "festival", "lunch"],
                      "complements": _c("onion_01", "atta_ww_01", "maida_01")},

    # SNACKS
    "sku_garlicbread_01": {"tags": ["italian", "dinner", "bread", "pasta-complement", "guests"],
                            "complements": _c("pasta_01", "pasta_sauce_01", "cheese_slices_01")},
    "sku_chips_classic_01": {"tags": ["chips", "salted", "snack", "tea-coffee-time", "late-night"],
                              "complements": _c("cola_01", "namkeen_mix_01", "lemonade_01")},
    "sku_namkeen_mix_01": {"tags": ["namkeen", "sev", "snack", "tea-coffee-time", "guests", "festival"],
                            "complements": _c("chips_classic_01", "biscuits_marie_01", "green_tea_01")},
    "sku_biscuits_marie_01": {"tags": ["biscuits", "tea-time", "tea-coffee-time", "breakfast", "kitchen-restock"],
                               "complements": _c("coffee_instant_01", "milk_01", "green_tea_01")},
    "sku_popcorn_bhutta_01": {"tags": ["popcorn", "masala", "snack", "late-night", "tea-coffee-time"],
                               "complements": _c("cola_01", "chips_classic_01", "lemonade_01")},
    "sku_nachos_01": {"tags": ["nachos", "party", "dip", "guests", "dinner"],
                       "complements": _c("party_supplies_set_01", "disposable_plates_01", "cola_01")},
    "sku_energy_bar_01": {"tags": ["energy-bar", "peanut", "snack", "wellness", "travel", "immunity"],
                           "complements": _c("dryfruit_mix_01", "multivitamin_01", "omega3_01")},
    "sku_dryfruit_mix_01": {"tags": ["dry-fruits", "premium", "healthy", "wellness", "festival", "gifting", "guests"],
                             "complements": _c("energy_bar_01", "chocolate_gift_box_01", "multivitamin_01")},
    "sku_cookies_choc_01": {"tags": ["cookies", "chocolate", "snack", "tea-coffee-time", "late-night"],
                             "complements": _c("coffee_instant_01", "milk_01", "charger_usbc_01")},
    "sku_pizza_bread_01": {"tags": ["pizza", "dinner", "bread", "guests", "kitchen-restock"],
                            "complements": _c("pasta_sauce_01", "cheese_slices_01", "capsicum_01")},

    # BEVERAGES
    "sku_cola_01": {"tags": ["cola", "soft-drink", "party", "guests", "late-night"],
                     "complements": _c("nachos_01", "party_supplies_set_01", "disposable_plates_01")},
    "sku_grape_juice_01": {"tags": ["juice", "grape", "dinner", "non-alcoholic", "guests", "festival"],
                            "complements": _c("pasta_01", "garlicbread_01", "chocolate_gift_box_01")},
    "sku_orange_juice_01": {"tags": ["juice", "orange", "breakfast", "wellness", "immunity"],
                             "complements": _c("biscuits_marie_01", "milk_01", "multivitamin_01")},
    "sku_soda_water_01": {"tags": ["soda", "mixer", "guests", "party", "summer"],
                           "complements": _c("lemon_01", "cola_01", "lemonade_01")},
    "sku_iced_tea_01": {"tags": ["iced-tea", "lemon", "summer", "tea-coffee-time"],
                         "complements": _c("lemon_01", "lemonade_01", "coconut_water_01")},
    "sku_coconut_water_01": {"tags": ["coconut-water", "natural", "summer", "wellness", "immunity"],
                              "complements": _c("lemon_01", "iced_tea_01", "electrolyte_powder_01")},
    "sku_energy_drink_01": {"tags": ["energy-drink", "caffeine", "late-night", "desk-setup", "wellness"],
                             "complements": _c("chips_classic_01", "charger_usbc_01", "multivitamin_01")},
    "sku_coffee_instant_01": {"tags": ["coffee", "instant", "tea-coffee-time", "breakfast", "late-night"],
                               "complements": _c("milk_01", "biscuits_marie_01", "melatonin_gummies_01", "sugar_01")},
    "sku_green_tea_01": {"tags": ["tea", "green-tea", "healthy", "wellness", "tea-coffee-time", "immunity"],
                          "complements": _c("biscuits_marie_01", "namkeen_mix_01", "lemon_01")},
    "sku_lemonade_01": {"tags": ["lemonade", "soft-drink", "summer", "party", "guests"],
                         "complements": _c("lemon_01", "soda_water_01", "chips_classic_01")},

    # DAIRY
    "sku_milk_01": {"tags": ["milk", "dairy", "daily", "breakfast", "tea-coffee-time", "kitchen-restock"],
                     "complements": _c("coffee_instant_01", "biscuits_marie_01", "sugar_01", "cookies_choc_01")},
    "sku_paneer_01": {"tags": ["paneer", "cottage-cheese", "dinner", "lunch", "kitchen-restock"],
                       "complements": _c("capsicum_01", "onion_01", "tomato_01")},
    "sku_parmesan_01": {"tags": ["cheese", "italian", "pasta-complement", "dinner", "guests"],
                         "complements": _c("pasta_01", "pasta_sauce_01", "garlicbread_01")},
    "sku_curd_01": {"tags": ["curd", "yogurt", "daily", "lunch", "wellness", "kitchen-restock"],
                     "complements": _c("rice_basmati_01", "buttermilk_01", "tomato_01")},
    "sku_butter_01": {"tags": ["butter", "dairy", "breakfast", "kitchen-restock"],
                       "complements": _c("atta_ww_01", "maida_01", "biscuits_marie_01")},
    "sku_ghee_01": {"tags": ["ghee", "cow-ghee", "kitchen-restock", "festival", "wellness", "immunity"],
                     "complements": _c("atta_ww_01", "toor_dal_01", "moong_dal_01")},
    "sku_cheese_slices_01": {"tags": ["cheese", "slices", "sandwich", "breakfast", "dinner", "kitchen-restock"],
                              "complements": _c("pizza_bread_01", "garlicbread_01", "capsicum_01")},
    "sku_yogurt_greek_01": {"tags": ["yogurt", "greek", "protein", "wellness", "breakfast", "immunity"],
                             "complements": _c("multivitamin_01", "omega3_01", "melatonin_gummies_01", "dryfruit_mix_01")},
    "sku_cream_01": {"tags": ["cream", "cooking", "dinner", "festival", "kitchen-restock"],
                      "complements": _c("pasta_sauce_01", "mushroom_01", "paneer_01")},
    "sku_buttermilk_01": {"tags": ["buttermilk", "chaas", "lunch", "summer", "wellness"],
                           "complements": _c("curd_01", "rice_basmati_01", "lemon_01")},

    # HOUSEHOLD
    "sku_dishwash_liquid_01": {"tags": ["dishwash", "cleaning", "kitchen-restock", "sink-care"],
                                "complements": _c("scrub_pad_01", "floor_cleaner_01", "tissue_roll_01")},
    "sku_detergent_powder_01": {"tags": ["detergent", "laundry", "cleaning", "kitchen-restock", "monsoon"],
                                 "complements": _c("floor_cleaner_01", "trash_bags_01", "air_freshener_01")},
    "sku_toilet_cleaner_01": {"tags": ["toilet-cleaner", "cleaning", "monsoon", "kitchen-restock"],
                               "complements": _c("floor_cleaner_01", "scrub_pad_01", "air_freshener_01")},
    "sku_floor_cleaner_01": {"tags": ["floor-cleaner", "cleaning", "monsoon", "kitchen-restock"],
                              "complements": _c("scrub_pad_01", "trash_bags_01", "air_freshener_01", "dishwash_liquid_01")},
    "sku_trash_bags_01": {"tags": ["garbage-bags", "trash", "cleaning", "baby-care", "kitchen-restock"],
                           "complements": _c("floor_cleaner_01", "diapers_01", "baby_wipes_01")},
    "sku_tissue_roll_01": {"tags": ["tissue", "kitchen", "kitchen-restock", "cleaning", "guests"],
                            "complements": _c("dishwash_liquid_01", "aluminium_foil_01", "scrub_pad_01")},
    "sku_mosquito_repellent_01": {"tags": ["mosquito", "repellent", "monsoon", "wellness", "first-aid"],
                                   "complements": _c("air_freshener_01", "electrolyte_powder_01", "antiseptic_liquid_01")},
    "sku_air_freshener_01": {"tags": ["air-freshener", "fragrance", "cleaning", "guests", "monsoon"],
                              "complements": _c("floor_cleaner_01", "toilet_cleaner_01", "mosquito_repellent_01")},
    "sku_scrub_pad_01": {"tags": ["scrub-pad", "cleaning", "kitchen-restock", "scrubber"],
                          "complements": _c("dishwash_liquid_01", "floor_cleaner_01", "toilet_cleaner_01")},
    "sku_aluminium_foil_01": {"tags": ["foil", "kitchen", "kitchen-restock", "guests", "dinner"],
                               "complements": _c("tissue_roll_01", "pizza_bread_01", "disposable_plates_01")},

    # FRESH
    "sku_tomato_01": {"tags": ["tomato", "vegetable", "lunch", "dinner", "kitchen-restock"],
                       "complements": _c("onion_01", "rice_basmati_01", "pasta_sauce_01")},
    "sku_basil_bunch_01": {"tags": ["basil", "herb", "italian", "pasta-complement", "dinner"],
                            "complements": _c("pasta_01", "pasta_sauce_01", "mushroom_01")},
    "sku_onion_01": {"tags": ["onion", "vegetable", "lunch", "dinner", "kitchen-restock"],
                      "complements": _c("tomato_01", "rice_basmati_01", "toor_dal_01", "garlic_pod_01")},
    "sku_spinach_01": {"tags": ["spinach", "leafy-green", "lunch", "wellness", "immunity", "kitchen-restock"],
                        "complements": _c("paneer_01", "onion_01", "garlic_pod_01")},
    "sku_capsicum_01": {"tags": ["capsicum", "vegetable", "dinner", "lunch", "kitchen-restock"],
                         "complements": _c("paneer_01", "pizza_bread_01", "onion_01")},
    "sku_banana_01": {"tags": ["banana", "fruit", "breakfast", "wellness", "immunity"],
                       "complements": _c("milk_01", "orange_juice_01", "yogurt_greek_01")},
    "sku_apple_01": {"tags": ["apple", "fruit", "breakfast", "wellness", "immunity", "guests"],
                      "complements": _c("banana_01", "orange_juice_01", "dryfruit_mix_01")},
    "sku_mushroom_01": {"tags": ["mushroom", "pasta-complement", "italian", "dinner", "guests"],
                         "complements": _c("pasta_01", "pasta_sauce_01", "basil_bunch_01")},
    "sku_garlic_pod_01": {"tags": ["garlic", "vegetable", "italian", "dinner", "kitchen-restock"],
                           "complements": _c("pasta_01", "onion_01", "pasta_sauce_01")},
    "sku_lemon_01": {"tags": ["lemon", "fruit", "summer", "kitchen-restock", "wellness"],
                      "complements": _c("iced_tea_01", "lemonade_01", "soda_water_01", "buttermilk_01")},

    # BEAUTY
    "sku_micellar_water_01": {"tags": ["micellar-water", "cleanser", "skincare", "personal-care", "grooming"],
                               "complements": _c("face_wash_01", "body_lotion_01", "face_mask_sheet_01", "face_serum_01")},
    "sku_face_wash_01": {"tags": ["face-wash", "skincare", "personal-care", "grooming", "cleanser"],
                          "complements": _c("micellar_water_01", "body_lotion_01", "sunscreen_01")},
    "sku_sunscreen_01": {"tags": ["sunscreen", "spf", "skincare", "personal-care", "summer", "travel"],
                          "complements": _c("face_wash_01", "lip_balm_01", "body_lotion_01")},
    "sku_lip_balm_01": {"tags": ["lip-balm", "skincare", "personal-care", "grooming", "travel"],
                         "complements": _c("sunscreen_01", "hand_cream_01", "body_lotion_01")},
    "sku_shampoo_01": {"tags": ["shampoo", "haircare", "personal-care", "grooming", "wellness"],
                        "complements": _c("body_lotion_01", "face_wash_01", "hand_cream_01")},
    "sku_body_lotion_01": {"tags": ["body-lotion", "skincare", "personal-care", "grooming", "monsoon"],
                            "complements": _c("micellar_water_01", "face_wash_01", "hand_cream_01")},
    "sku_face_serum_01": {"tags": ["serum", "vitamin-c", "skincare", "personal-care", "grooming"],
                           "complements": _c("micellar_water_01", "face_wash_01", "sunscreen_01")},
    "sku_kajal_01": {"tags": ["kajal", "makeup", "personal-care", "grooming", "guests", "party"],
                      "complements": _c("face_wash_01", "lip_balm_01", "micellar_water_01")},
    "sku_hand_cream_01": {"tags": ["hand-cream", "skincare", "personal-care", "grooming", "monsoon"],
                           "complements": _c("body_lotion_01", "lip_balm_01", "micellar_water_01")},
    "sku_face_mask_sheet_01": {"tags": ["sheet-mask", "skincare", "personal-care", "grooming", "guests"],
                                "complements": _c("micellar_water_01", "face_serum_01", "body_lotion_01")},

    # BABY
    "sku_diapers_01": {"tags": ["diapers", "baby", "baby-care", "daily", "hygiene"],
                        "complements": _c("baby_wipes_01", "baby_powder_01", "trash_bags_01", "baby_food_cereal_01")},
    "sku_baby_wipes_01": {"tags": ["wipes", "baby", "baby-care", "hygiene", "travel"],
                           "complements": _c("diapers_01", "baby_lotion_01", "baby_powder_01")},
    "sku_baby_lotion_01": {"tags": ["baby-lotion", "skincare", "baby-care", "grooming", "daily"],
                            "complements": _c("baby_wipes_01", "baby_oil_01", "baby_soap_01")},
    "sku_baby_shampoo_01": {"tags": ["baby-shampoo", "haircare", "baby-care", "grooming", "daily"],
                             "complements": _c("baby_soap_01", "baby_lotion_01", "baby_oil_01")},
    "sku_baby_powder_01": {"tags": ["baby-powder", "skincare", "baby-care", "hygiene", "grooming"],
                            "complements": _c("diapers_01", "baby_wipes_01", "baby_oil_01")},
    "sku_baby_food_cereal_01": {"tags": ["baby-food", "cereal", "baby-care", "breakfast", "wellness"],
                                 "complements": _c("diapers_01", "baby_wipes_01", "baby_bottle_01")},
    "sku_baby_oil_01": {"tags": ["baby-oil", "skincare", "baby-care", "grooming", "daily"],
                         "complements": _c("baby_lotion_01", "baby_powder_01", "baby_soap_01")},
    "sku_baby_soap_01": {"tags": ["baby-soap", "skincare", "baby-care", "grooming", "hygiene"],
                          "complements": _c("baby_shampoo_01", "baby_lotion_01", "baby_oil_01")},
    "sku_pacifier_01": {"tags": ["pacifier", "feeding", "baby-care", "travel", "daily"],
                         "complements": _c("baby_bottle_01", "baby_wipes_01", "diapers_01")},
    "sku_baby_bottle_01": {"tags": ["feeding-bottle", "feeding", "baby-care", "travel", "daily"],
                            "complements": _c("pacifier_01", "baby_food_cereal_01", "baby_wipes_01")},

    # PHARMA
    "sku_melatonin_gummies_01": {"tags": ["melatonin", "sleep", "wellness", "late-night", "tea-coffee-time"],
                                  "complements": _c("coffee_instant_01", "green_tea_01", "multivitamin_01", "yogurt_greek_01")},
    "sku_paracetamol_01": {"tags": ["paracetamol", "medicine", "first-aid", "wellness", "immunity"],
                            "complements": _c("bandaid_01", "antiseptic_liquid_01", "thermometer_01")},
    "sku_multivitamin_01": {"tags": ["multivitamin", "wellness", "immunity", "breakfast", "daily"],
                             "complements": _c("yogurt_greek_01", "omega3_01", "dryfruit_mix_01", "melatonin_gummies_01")},
    "sku_bandaid_01": {"tags": ["bandage", "first-aid", "wellness", "travel"],
                        "complements": _c("antiseptic_liquid_01", "paracetamol_01", "thermometer_01")},
    "sku_antiseptic_liquid_01": {"tags": ["antiseptic", "first-aid", "wellness", "travel"],
                                  "complements": _c("bandaid_01", "paracetamol_01", "hand_sanitizer_01")},
    "sku_cough_syrup_01": {"tags": ["cough-syrup", "medicine", "first-aid", "wellness", "immunity", "monsoon"],
                            "complements": _c("paracetamol_01", "thermometer_01", "electrolyte_powder_01")},
    "sku_hand_sanitizer_01": {"tags": ["sanitizer", "hygiene", "first-aid", "wellness", "travel"],
                               "complements": _c("antiseptic_liquid_01", "bandaid_01", "baby_wipes_01")},
    "sku_thermometer_01": {"tags": ["thermometer", "device", "first-aid", "wellness"],
                            "complements": _c("paracetamol_01", "cough_syrup_01", "bandaid_01")},
    "sku_omega3_01": {"tags": ["omega-3", "supplement", "wellness", "immunity", "breakfast"],
                       "complements": _c("multivitamin_01", "yogurt_greek_01", "energy_bar_01")},
    "sku_electrolyte_powder_01": {"tags": ["electrolyte", "hydration", "wellness", "summer", "immunity"],
                                   "complements": _c("coconut_water_01", "cough_syrup_01", "mosquito_repellent_01")},

    # ELECTRONICS
    "sku_charger_usbc_01": {"tags": ["charger", "usb-c", "fast-charging", "desk-setup", "travel"],
                             "complements": _c("charging_cable_01", "powerbank_01", "cookies_choc_01")},
    "sku_charging_cable_01": {"tags": ["cable", "usb-c", "desk-setup", "travel", "charging"],
                               "complements": _c("charger_usbc_01", "powerbank_01", "extension_board_01")},
    "sku_earphones_01": {"tags": ["earphones", "audio", "desk-setup", "travel", "late-night"],
                          "complements": _c("phone_stand_01", "charger_usbc_01", "earbuds_case_01")},
    "sku_powerbank_01": {"tags": ["powerbank", "charging", "travel", "desk-setup", "late-night"],
                          "complements": _c("charging_cable_01", "charger_usbc_01", "led_torch_01")},
    "sku_bulb_smart_01": {"tags": ["smart-bulb", "led", "home", "desk-setup", "festival"],
                           "complements": _c("extension_board_01", "led_torch_01", "batteries_aa_01")},
    "sku_extension_board_01": {"tags": ["extension-board", "electrical", "desk-setup", "home", "travel"],
                                "complements": _c("charging_cable_01", "bulb_smart_01", "batteries_aa_01")},
    "sku_batteries_aa_01": {"tags": ["batteries", "aa", "desk-setup", "home", "kitchen-restock"],
                             "complements": _c("led_torch_01", "bulb_smart_01", "extension_board_01")},
    "sku_phone_stand_01": {"tags": ["phone-stand", "accessory", "desk-setup", "travel", "late-night"],
                            "complements": _c("earphones_01", "charger_usbc_01", "charging_cable_01")},
    "sku_led_torch_01": {"tags": ["torch", "led", "emergency", "monsoon", "travel"],
                          "complements": _c("batteries_aa_01", "powerbank_01", "bulb_smart_01")},
    "sku_earbuds_case_01": {"tags": ["earbuds", "audio", "wireless", "desk-setup", "travel", "late-night"],
                             "complements": _c("earphones_01", "charger_usbc_01", "phone_stand_01")},

    # PARTY_GIFTING
    "sku_party_supplies_set_01": {"tags": ["party", "birthday", "balloons", "streamers", "festival", "guests"],
                                   "complements": _c("candles_bday_01", "balloons_01", "confetti_01", "disposable_plates_01")},
    "sku_candles_bday_01": {"tags": ["candles", "birthday", "party", "festival", "gifting"],
                             "complements": _c("party_supplies_set_01", "balloons_01", "chocolate_gift_box_01")},
    "sku_balloons_01": {"tags": ["balloons", "party", "birthday", "festival", "guests"],
                         "complements": _c("party_supplies_set_01", "confetti_01", "candles_bday_01")},
    "sku_gift_wrap_01": {"tags": ["gift-wrap", "gifting", "festival", "guests"],
                          "complements": _c("ribbon_roll_01", "greeting_card_01", "chocolate_gift_box_01")},
    "sku_greeting_card_01": {"tags": ["greeting-card", "gifting", "festival", "guests"],
                              "complements": _c("gift_wrap_01", "chocolate_gift_box_01", "ribbon_roll_01")},
    "sku_party_hats_01": {"tags": ["party-hats", "birthday", "party", "festival", "guests"],
                           "complements": _c("party_supplies_set_01", "balloons_01", "confetti_01")},
    "sku_confetti_01": {"tags": ["confetti", "party", "birthday", "festival", "guests"],
                         "complements": _c("party_supplies_set_01", "balloons_01", "party_hats_01")},
    "sku_chocolate_gift_box_01": {"tags": ["chocolate", "gifting", "festival", "guests", "party"],
                                   "complements": _c("gift_wrap_01", "greeting_card_01", "dryfruit_mix_01")},
    "sku_disposable_plates_01": {"tags": ["plates", "party", "guests", "festival"],
                                  "complements": _c("party_supplies_set_01", "nachos_01", "cola_01")},
    "sku_ribbon_roll_01": {"tags": ["ribbon", "gifting", "festival", "guests"],
                            "complements": _c("gift_wrap_01", "greeting_card_01", "candles_bday_01")},

    # PET
    "sku_dog_food_01": {"tags": ["dog-food", "pet", "pet-care", "kitchen-restock", "daily"],
                         "complements": _c("pet_treats_01", "pet_bowl_01", "pet_toy_01")},
    "sku_cat_food_01": {"tags": ["cat-food", "pet", "pet-care", "kitchen-restock", "daily"],
                         "complements": _c("litter_01", "pet_bowl_01", "pet_treats_01")},
    "sku_pet_treats_01": {"tags": ["pet-treats", "training", "pet-care", "dog"],
                           "complements": _c("dog_food_01", "pet_toy_01", "pet_leash_01")},
    "sku_pet_shampoo_01": {"tags": ["pet-shampoo", "grooming", "pet-care", "hygiene", "daily"],
                            "complements": _c("pet_toy_01", "pet_bowl_01", "dog_food_01")},
    "sku_litter_01": {"tags": ["cat-litter", "pet", "pet-care", "kitchen-restock", "hygiene"],
                       "complements": _c("cat_food_01", "pet_bowl_01", "trash_bags_01")},
    "sku_pet_toy_01": {"tags": ["pet-toy", "chew", "pet-care", "dog", "training"],
                        "complements": _c("dog_food_01", "pet_treats_01", "pet_leash_01")},
    "sku_pet_bowl_01": {"tags": ["pet-bowl", "feeding", "pet-care", "dog", "cat"],
                         "complements": _c("dog_food_01", "cat_food_01", "pet_shampoo_01")},
    "sku_pet_leash_01": {"tags": ["pet-leash", "walking", "pet-care", "dog", "travel"],
                          "complements": _c("pet_toy_01", "pet_treats_01", "dog_food_01")},
    "sku_bird_seed_01": {"tags": ["bird-seed", "pet", "pet-care", "kitchen-restock", "daily"],
                          "complements": _c("pet_bowl_01", "fish_food_01", "dog_food_01")},
    "sku_fish_food_01": {"tags": ["fish-food", "pet", "pet-care", "kitchen-restock", "daily"],
                          "complements": _c("bird_seed_01", "pet_bowl_01", "litter_01")},
}
