"""Generates /shared/catalog.json and persona profiles (priya.json, ishaan.json)
from the structured data below. Source of truth for SKU content; re-run after
editing this file to regenerate the JSON (`python scripts/seed_catalog.py`).

Schema follows docs/datamodel.md sections 1-3.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHARED = os.path.join(ROOT, "shared")

CATEGORIES = [
    {"category_id": "staples", "name": "Atta, Rice & Dal", "icon": "wheat",
     "risk_tier": "low", "trust_template": ["expiry", "ingredient"]},
    {"category_id": "snacks", "name": "Chips & Namkeen", "icon": "cookie",
     "risk_tier": "low", "trust_template": ["expiry", "ingredient"]},
    {"category_id": "beverages", "name": "Cold Drinks & Juices", "icon": "cup-soda",
     "risk_tier": "low", "trust_template": ["expiry"]},
    {"category_id": "dairy", "name": "Dairy, Bread & Eggs", "icon": "milk",
     "risk_tier": "medium", "trust_template": ["expiry", "freshness"]},
    {"category_id": "household", "name": "Cleaning & Household", "icon": "spray-can",
     "risk_tier": "low", "trust_template": ["quantity"]},
    {"category_id": "fresh", "name": "Fruits & Vegetables", "icon": "carrot",
     "risk_tier": "high", "trust_template": ["freshness", "sourcing", "return"]},
    {"category_id": "beauty", "name": "Beauty & Personal Care", "icon": "sparkles",
     "risk_tier": "high", "trust_template": ["authenticity", "ingredient", "return"]},
    {"category_id": "baby", "name": "Baby Care", "icon": "baby",
     "risk_tier": "high", "trust_template": ["authenticity", "expiry", "return"]},
    {"category_id": "pharma", "name": "Pharmacy & Wellness", "icon": "pill",
     "risk_tier": "high", "trust_template": ["authenticity", "expiry"]},
    {"category_id": "electronics", "name": "Electronics Essentials", "icon": "plug-zap",
     "risk_tier": "high", "trust_template": ["compatibility", "warranty", "return"]},
    {"category_id": "party_gifting", "name": "Party & Gifting", "icon": "gift",
     "risk_tier": "medium", "trust_template": ["quantity"]},
    {"category_id": "pet", "name": "Pet Care", "icon": "paw-print",
     "risk_tier": "medium", "trust_template": ["ingredient", "expiry"]},
]

# Each SKU tuple: (slug, name, unit, price, mrp, veg, tags, description,
#                   complements(slugs), trust_fact_labels(matches category trust_template order),
#                   has_anchor bool, deal dict|None)

SKUS_BY_CATEGORY = {
"staples": [
    ("atta_ww_01", "Whole Wheat Atta", "5 kg", 259, 279, True,
     ["atta", "wheat", "flour", "staple", "chakki-fresh"],
     "Stone-ground 100% whole wheat atta, no maida blend.",
     [], ["Expiry: Jun 2027", "100% whole wheat, no maida"], False, None),
    ("maida_01", "Refined Maida Flour", "1 kg", 55, 60, True,
     ["maida", "refined-flour", "baking"],
     "Finely refined maida for baking and frying.",
     [], ["Expiry: Apr 2027", "Refined wheat flour (maida)"], False, None),
    ("rice_basmati_01", "Basmati Rice", "5 kg", 549, 599, True,
     ["rice", "basmati", "staple"],
     "Aged long-grain basmati rice.",
     [], ["Expiry: Dec 2027", "Aged, single-origin grain"], False, {"label": "8% OFF", "lowest_30d": False}),
    ("toor_dal_01", "Toor Dal", "1 kg", 165, 180, True,
     ["dal", "toor", "pulses", "protein"],
     "Unpolished toor dal, high in protein.",
     [], ["Expiry: Mar 2027", "Unpolished, no added color"], False, None),
    ("moong_dal_01", "Moong Dal", "1 kg", 145, 155, True,
     ["dal", "moong", "pulses", "protein"],
     "Split yellow moong dal.",
     [], ["Expiry: Mar 2027", "100% natural, no polish"], False, None),
    ("sugar_01", "Sugar", "1 kg", 48, 52, True,
     ["sugar", "sweetener"],
     "Refined white sugar.",
     [], ["Expiry: Dec 2028", "No added additives"], False, None),
    ("salt_01", "Iodized Salt", "1 kg", 24, 26, True,
     ["salt", "iodized"],
     "Vacuum-evaporated iodized salt.",
     [], ["Expiry: Dec 2028", "Iodine fortified"], False, None),
    ("pasta_01", "Penne Pasta", "500 g", 89, 99, True,
     ["italian", "dinner", "pasta", "durum-wheat"],
     "Durum wheat penne pasta, cooks in 11 minutes.",
     ["garlicbread_01", "pasta_sauce_01", "parmesan_01", "basil_bunch_01", "mushroom_01"],
     ["Expiry: Nov 2026", "100% durum wheat semolina"], True, None),
    ("pasta_sauce_01", "Tomato Basil Pasta Sauce", "350 g", 149, 169, True,
     ["italian", "dinner", "pasta-complement", "sauce"],
     "Slow-cooked tomato basil sauce, no artificial color.",
     ["pasta_01", "garlicbread_01"],
     ["Expiry: Aug 2026", "No artificial color or preservatives"], True, {"label": "12% OFF", "lowest_30d": True}),
    ("besan_01", "Besan (Gram Flour)", "1 kg", 89, 95, True,
     ["besan", "gram-flour", "staple"],
     "Roasted gram flour for pakoras and curries.",
     [], ["Expiry: Feb 2027", "100% chana dal ground"], False, None),
],
"snacks": [
    ("garlicbread_01", "Baker's Dozen Garlic Bread", "250 g", 99, 115, True,
     ["italian", "dinner", "bread", "pasta-complement"],
     "Stone-baked garlic bread, ready in 5 min.",
     ["pasta_01", "pasta_sauce_01"],
     ["Expiry: Nov 2026", "Whole wheat, no maida"], True, {"label": "14% OFF", "lowest_30d": False}),
    ("chips_classic_01", "Classic Salted Potato Chips", "52 g", 20, 20, True,
     ["chips", "salted", "snack"],
     "Thin-cut, kettle-fried potato chips.",
     [], ["Expiry: Jan 2027", "No artificial flavors"], False, None),
    ("namkeen_mix_01", "Bhujia Sev Mix", "200 g", 65, 70, True,
     ["namkeen", "sev", "snack"],
     "Crunchy besan sev with peanuts and spices.",
     [], ["Expiry: Mar 2027", "Cooked in refined sunflower oil"], False, None),
    ("biscuits_marie_01", "Marie Gold Biscuits", "250 g", 35, 40, True,
     ["biscuits", "tea-time"],
     "Light, crisp tea-time biscuits.",
     [], ["Expiry: Feb 2027", "No trans fat"], False, None),
    ("popcorn_bhutta_01", "Masala Corn Puffs", "60 g", 20, 20, True,
     ["popcorn", "masala", "snack"],
     "Roasted corn puffs with tangy masala.",
     [], ["Expiry: Dec 2026", "Roasted, not fried"], False, None),
    ("nachos_01", "Nacho Chips with Salsa Dip", "150 g", 99, 110, True,
     ["nachos", "party", "dip"],
     "Corn nachos with a tangy tomato salsa dip.",
     ["party_supplies_set_01"],
     ["Expiry: Feb 2027", "No artificial color"], True, None),
    ("energy_bar_01", "Peanut Chikki Energy Bar", "40 g", 25, 25, True,
     ["energy-bar", "peanut", "snack"],
     "Jaggery-roasted peanut chikki bar.",
     [], ["Expiry: Jun 2027", "No refined sugar"], False, None),
    ("dryfruit_mix_01", "Premium Dry Fruit Mix", "200 g", 349, 399, True,
     ["dry-fruits", "premium", "healthy"],
     "Almonds, cashews and raisins mix.",
     [], ["Expiry: Sep 2026", "No added preservatives"], False, {"label": "13% OFF", "lowest_30d": False}),
    ("cookies_choc_01", "Chocolate Chip Cookies", "150 g", 79, 89, True,
     ["cookies", "chocolate", "snack"],
     "Butter cookies loaded with choc chips.",
     [], ["Expiry: Jan 2027", "Real cocoa, no compound"], False, None),
    ("pizza_bread_01", "Mini Pizza Base 4-pack", "200 g", 79, 89, True,
     ["pizza", "dinner", "bread"],
     "Ready-to-top mini pizza bases.",
     ["pasta_sauce_01", "cheese_slices_01"],
     ["Expiry: Oct 2026", "No maida — multigrain base"], True, None),
],
"beverages": [
    ("cola_01", "Cola Soft Drink", "750 ml", 40, 40, True,
     ["cola", "soft-drink"],
     "Classic carbonated cola.",
     [], ["Expiry: Apr 2027"], False, None),
    ("grape_juice_01", "Sparkling Grape Juice", "1 L", 129, 149, True,
     ["juice", "grape", "dinner", "non-alcoholic"],
     "Sparkling non-alcoholic grape juice, dinner-table favourite.",
     ["pasta_01", "garlicbread_01"],
     ["Expiry: Mar 2027"], True, None),
    ("orange_juice_01", "100% Orange Juice", "1 L", 149, 165, True,
     ["juice", "orange", "breakfast"],
     "No added sugar, 100% fruit juice.",
     [], ["Expiry: Feb 2027"], False, None),
    ("soda_water_01", "Soda Water", "750 ml", 30, 30, True,
     ["soda", "mixer"],
     "Plain carbonated soda water.",
     [], ["Expiry: Jun 2027"], False, None),
    ("iced_tea_01", "Lemon Iced Tea", "500 ml", 45, 50, True,
     ["iced-tea", "lemon"],
     "Chilled lemon iced tea.",
     [], ["Expiry: May 2027"], False, None),
    ("coconut_water_01", "Tender Coconut Water", "200 ml", 45, 45, True,
     ["coconut-water", "natural"],
     "Packaged tender coconut water.",
     [], ["Expiry: Jan 2027"], False, None),
    ("energy_drink_01", "Energy Drink", "250 ml", 110, 120, True,
     ["energy-drink", "caffeine"],
     "Caffeinated energy drink.",
     [], ["Expiry: Sep 2026"], False, None),
    ("coffee_instant_01", "Instant Coffee", "100 g", 249, 279, True,
     ["coffee", "instant"],
     "Freeze-dried instant coffee granules.",
     [], ["Expiry: Dec 2027"], False, {"label": "11% OFF", "lowest_30d": True}),
    ("green_tea_01", "Green Tea Bags", "25 ct", 149, 165, True,
     ["tea", "green-tea", "healthy"],
     "Antioxidant-rich green tea bags.",
     [], ["Expiry: Oct 2027"], False, None),
    ("lemonade_01", "Fizzy Lemonade", "750 ml", 40, 40, True,
     ["lemonade", "soft-drink"],
     "Tangy fizzy lemonade.",
     [], ["Expiry: Apr 2027"], False, None),
],
"dairy": [
    ("milk_01", "Toned Milk", "1 L", 66, 66, True,
     ["milk", "dairy", "daily"],
     "Pasteurized toned milk.",
     [], ["Expiry: 2 days from delivery", "Pasteurized same-day"], False, None),
    ("paneer_01", "Fresh Paneer Block", "200 g", 89, 95, True,
     ["paneer", "cottage-cheese"],
     "Soft, fresh cottage cheese block.",
     [], ["Expiry: 4 days from delivery", "Made from fresh milk, no preservatives"], False, None),
    ("parmesan_01", "Aged Hard Cheese Block", "200 g", 349, 399, True,
     ["cheese", "italian", "pasta-complement"],
     "Aged hard cheese for grating over pasta.",
     ["pasta_01", "pasta_sauce_01"],
     ["Expiry: Jan 2027", "Aged 12 months, brand-sealed"], True, {"label": "12% OFF", "lowest_30d": False}),
    ("curd_01", "Fresh Curd", "400 g", 40, 42, True,
     ["curd", "yogurt", "daily"],
     "Thick set curd.",
     [], ["Expiry: 3 days from delivery", "Set daily, no added sugar"], False, None),
    ("butter_01", "Salted Butter", "100 g", 55, 58, True,
     ["butter", "dairy"],
     "Creamy salted table butter.",
     [], ["Expiry: Feb 2027", "Made from fresh cream"], False, None),
    ("ghee_01", "Pure Cow Ghee", "500 ml", 349, 379, True,
     ["ghee", "cow-ghee"],
     "Traditional bilona-method cow ghee.",
     [], ["Expiry: Nov 2027", "100% pure, no vanaspati"], False, None),
    ("cheese_slices_01", "Processed Cheese Slices", "10 pk", 99, 110, True,
     ["cheese", "slices", "sandwich"],
     "Ready-to-melt cheese slices.",
     ["pizza_bread_01"], ["Expiry: Mar 2027", "No added color"], False, None),
    ("yogurt_greek_01", "Greek Yogurt Cup", "100 g", 45, 50, True,
     ["yogurt", "greek", "protein"],
     "Thick, high-protein Greek yogurt.",
     [], ["Expiry: 6 days from delivery", "Double the protein of regular curd"], False, None),
    ("cream_01", "Fresh Cream", "200 ml", 65, 70, True,
     ["cream", "cooking"],
     "Fresh dairy cream for cooking and desserts.",
     [], ["Expiry: 5 days from delivery", "Made from fresh milk"], False, None),
    ("buttermilk_01", "Spiced Buttermilk", "200 ml", 20, 20, True,
     ["buttermilk", "chaas"],
     "Refreshing spiced buttermilk.",
     [], ["Expiry: 2 days from delivery", "No added preservatives"], False, None),
],
"household": [
    ("dishwash_liquid_01", "Dishwash Liquid", "500 ml", 99, 110, True,
     ["dishwash", "cleaning"],
     "Grease-cutting dishwash liquid.",
     [], ["500ml — approx. 150 washes"], False, None),
    ("detergent_powder_01", "Detergent Powder", "1 kg", 149, 165, True,
     ["detergent", "laundry"],
     "Stain-removing detergent powder.",
     [], ["1kg — approx. 12 loads"], False, {"label": "10% OFF", "lowest_30d": False}),
    ("toilet_cleaner_01", "Toilet Cleaner", "500 ml", 89, 99, True,
     ["toilet-cleaner", "cleaning"],
     "Disinfectant toilet cleaner.",
     [], ["500ml — approx. 20 uses"], False, None),
    ("floor_cleaner_01", "Floor Cleaner", "1 L", 129, 145, True,
     ["floor-cleaner", "cleaning"],
     "Disinfectant floor cleaner, fresh scent.",
     [], ["1L — approx. 15 mopping sessions"], False, None),
    ("trash_bags_01", "Garbage Bags", "30 pc", 149, 165, True,
     ["garbage-bags", "trash"],
     "Leak-proof medium garbage bags.",
     [], ["30 bags per roll"], False, None),
    ("tissue_roll_01", "Kitchen Tissue Roll", "2 pk", 99, 110, True,
     ["tissue", "kitchen"],
     "Absorbent kitchen tissue rolls.",
     [], ["2 rolls, 60 sheets each"], False, None),
    ("mosquito_repellent_01", "Mosquito Repellent Liquid Refill", "45 ml", 89, 95, True,
     ["mosquito", "repellent"],
     "Liquid vaporizer refill.",
     [], ["45ml — lasts 45 nights"], False, None),
    ("air_freshener_01", "Room Air Freshener Spray", "300 ml", 199, 219, True,
     ["air-freshener", "fragrance"],
     "Long-lasting room fragrance spray.",
     [], ["300ml — approx. 300 sprays"], False, None),
    ("scrub_pad_01", "Scrub Pad", "3 pk", 45, 50, True,
     ["scrub-pad", "cleaning"],
     "Heavy-duty kitchen scrub pads.",
     [], ["Pack of 3"], False, None),
    ("aluminium_foil_01", "Aluminium Foil", "5 m", 79, 85, True,
     ["foil", "kitchen"],
     "Food-grade aluminium foil roll.",
     [], ["5 metre roll"], False, None),
],
"fresh": [
    ("tomato_01", "Fresh Tomatoes", "500 g", 29, 35, True,
     ["tomato", "vegetable"],
     "Farm-fresh, hand-picked tomatoes.",
     [], ["Harvested within 48 hrs", "Sourced from local farms", "Free replacement if not fresh"], True, None),
    ("basil_bunch_01", "Fresh Basil Bunch", "50 g", 39, 45, True,
     ["basil", "herb", "italian", "pasta-complement"],
     "Aromatic fresh basil, perfect for pasta.",
     ["pasta_01", "pasta_sauce_01"],
     ["Harvested within 24 hrs", "Grown pesticide-light", "Free replacement if wilted"], True, None),
    ("onion_01", "Onions", "1 kg", 35, 40, True,
     ["onion", "vegetable"],
     "Everyday cooking onions.",
     [], ["Harvested within 72 hrs", "Sourced from Nashik belt", "Free replacement if spoiled"], False, None),
    ("spinach_01", "Fresh Spinach", "200 g", 25, 30, True,
     ["spinach", "leafy-green"],
     "Washed and trimmed spinach leaves.",
     [], ["Harvested within 24 hrs", "Sourced from local farms", "Free replacement if wilted"], False, None),
    ("capsicum_01", "Capsicum", "250 g", 35, 40, True,
     ["capsicum", "vegetable"],
     "Crisp green capsicum.",
     [], ["Harvested within 48 hrs", "Sourced from local farms", "Free replacement if spoiled"], False, None),
    ("banana_01", "Robusta Bananas", "6 pc", 42, 48, True,
     ["banana", "fruit"],
     "Naturally ripened bananas.",
     [], ["Harvested within 72 hrs", "Naturally ripened, no carbide", "Free replacement if overripe"], False, None),
    ("apple_01", "Shimla Apples", "4 pc", 149, 169, True,
     ["apple", "fruit"],
     "Crisp Himachal Shimla apples.",
     [], ["Harvested within a week", "Sourced from Himachal orchards", "Free replacement if bruised"], False, {"label": "11% OFF", "lowest_30d": False}),
    ("mushroom_01", "Button Mushrooms", "200 g", 55, 60, True,
     ["mushroom", "pasta-complement"],
     "Fresh white button mushrooms.",
     ["pasta_01", "pasta_sauce_01"],
     ["Harvested within 24 hrs", "Farm-cultivated, pesticide-light", "Free replacement if spoiled"], True, None),
    ("garlic_pod_01", "Garlic Pods", "100 g", 25, 28, True,
     ["garlic", "vegetable"],
     "Fresh garlic pods.",
     ["pasta_01"], ["Harvested within a week", "Sourced from local farms", "Free replacement if spoiled"], False, None),
    ("lemon_01", "Lemons", "4 pc", 20, 24, True,
     ["lemon", "fruit"],
     "Juicy fresh lemons.",
     [], ["Harvested within 72 hrs", "Sourced from local farms", "Free replacement if dried out"], False, None),
],
"beauty": [
    ("micellar_water_01", "Micellar Cleansing Water", "200 ml", 349, 399, True,
     ["micellar-water", "cleanser", "skincare"],
     "Gentle no-rinse micellar cleansing water.",
     [], ["100% authentic, brand-sealed", "No parabens, no sulphates", "Easy return if unopened"], True, {"label": "13% OFF", "lowest_30d": True}),
    ("face_wash_01", "Foaming Face Wash", "100 ml", 199, 225, True,
     ["face-wash", "skincare"],
     "Gentle foaming daily face wash.",
     [], ["100% authentic, brand-sealed", "Soap-free formula", "Easy return if unopened"], False, None),
    ("sunscreen_01", "SPF 50 Sunscreen Lotion", "50 ml", 449, 499, True,
     ["sunscreen", "spf", "skincare"],
     "Broad-spectrum SPF 50 sunscreen.",
     [], ["100% authentic, brand-sealed", "No white cast, non-greasy", "Easy return if unopened"], True, None),
    ("lip_balm_01", "Shea Butter Lip Balm", "4 g", 99, 110, True,
     ["lip-balm", "skincare"],
     "Moisturizing shea butter lip balm.",
     [], ["100% authentic, brand-sealed", "Shea butter, no mineral oil", "Easy return if unopened"], False, None),
    ("shampoo_01", "Anti-Dandruff Shampoo", "180 ml", 199, 220, True,
     ["shampoo", "haircare"],
     "Anti-dandruff, clinically tested shampoo.",
     [], ["100% authentic, brand-sealed", "Clinically tested formula", "Easy return if unopened"], False, None),
    ("body_lotion_01", "Body Lotion", "200 ml", 175, 195, True,
     ["body-lotion", "skincare"],
     "24-hour moisturizing body lotion.",
     [], ["100% authentic, brand-sealed", "Non-sticky, fast-absorbing", "Easy return if unopened"], False, None),
    ("face_serum_01", "Vitamin C Face Serum", "30 ml", 549, 599, True,
     ["serum", "vitamin-c", "skincare"],
     "Brightening vitamin C face serum.",
     [], ["100% authentic, brand-sealed", "10% Vitamin C concentration", "Easy return if unopened"], True, None),
    ("kajal_01", "Smudge-Proof Kajal", "0.35 g", 149, 165, True,
     ["kajal", "makeup"],
     "Long-wear smudge-proof kajal.",
     [], ["100% authentic, brand-sealed", "Ophthalmologist tested", "Easy return if unopened"], False, None),
    ("hand_cream_01", "Hand Cream", "50 g", 125, 140, True,
     ["hand-cream", "skincare"],
     "Deep moisturizing hand cream.",
     [], ["100% authentic, brand-sealed", "Glycerin-based formula", "Easy return if unopened"], False, None),
    ("face_mask_sheet_01", "Hydrating Sheet Mask", "1 pc", 79, 89, True,
     ["sheet-mask", "skincare"],
     "Single-use hydrating sheet mask.",
     [], ["100% authentic, brand-sealed", "Aloe vera infused", "Easy return if unopened"], False, None),
],
"baby": [
    ("diapers_01", "Baby Diapers Medium", "20 pc", 449, 499, True,
     ["diapers", "baby"],
     "Ultra-absorbent medium diapers.",
     [], ["100% authentic, sealed pack", "Expiry: Oct 2028", "Easy return if unopened"], True, None),
    ("baby_wipes_01", "Baby Wipes", "80 pc", 149, 165, True,
     ["wipes", "baby"],
     "Fragrance-free baby wipes.",
     [], ["100% authentic, sealed pack", "Expiry: Aug 2028", "Easy return if unopened"], False, None),
    ("baby_lotion_01", "Baby Lotion", "100 ml", 175, 195, True,
     ["baby-lotion", "skincare"],
     "Mild, tear-free baby lotion.",
     [], ["100% authentic, sealed pack", "Expiry: Jul 2027", "Easy return if unopened"], False, None),
    ("baby_shampoo_01", "Tear-Free Baby Shampoo", "100 ml", 165, 180, True,
     ["baby-shampoo", "haircare"],
     "No-tears formula baby shampoo.",
     [], ["100% authentic, sealed pack", "Expiry: Jun 2027", "Easy return if unopened"], False, None),
    ("baby_powder_01", "Baby Powder", "100 g", 99, 110, True,
     ["baby-powder", "skincare"],
     "Talc-free baby powder.",
     [], ["100% authentic, sealed pack", "Expiry: Sep 2027", "Easy return if unopened"], False, None),
    ("baby_food_cereal_01", "Baby Cereal", "300 g", 249, 275, True,
     ["baby-food", "cereal"],
     "Iron-fortified baby cereal, 6 months+.",
     [], ["100% authentic, sealed pack", "Expiry: Mar 2027", "Easy return if unopened"], True, None),
    ("baby_oil_01", "Baby Massage Oil", "100 ml", 145, 160, True,
     ["baby-oil", "skincare"],
     "Nourishing baby massage oil.",
     [], ["100% authentic, sealed pack", "Expiry: May 2027", "Easy return if unopened"], False, None),
    ("baby_soap_01", "Baby Soap Bar", "75 g", 65, 72, True,
     ["baby-soap", "skincare"],
     "Mild moisturizing baby soap.",
     [], ["100% authentic, sealed pack", "Expiry: Apr 2027", "Easy return if unopened"], False, None),
    ("pacifier_01", "Silicone Pacifier", "1 pc", 199, 220, True,
     ["pacifier", "feeding"],
     "BPA-free silicone pacifier.",
     [], ["100% authentic, sealed pack", "BPA-free certified", "Easy return if unopened"], False, None),
    ("baby_bottle_01", "Feeding Bottle", "250 ml", 299, 329, True,
     ["feeding-bottle", "feeding"],
     "Anti-colic feeding bottle.",
     [], ["100% authentic, sealed pack", "BPA-free certified", "Easy return if unopened"], False, None),
],
"pharma": [
    ("melatonin_gummies_01", "Melatonin Sleep Gummies", "30 ct", 449, 499, True,
     ["melatonin", "sleep", "wellness"],
     "Melatonin gummies for occasional sleeplessness.",
     [], ["100% authentic, licensed seller", "Expiry: Dec 2027"], True, {"label": "10% OFF", "lowest_30d": True}),
    ("paracetamol_01", "Paracetamol Tablets", "10 ct", 20, 22, True,
     ["paracetamol", "medicine"],
     "Standard paracetamol tablets.",
     [], ["100% authentic, licensed seller", "Expiry: Jan 2028"], False, None),
    ("multivitamin_01", "Daily Multivitamin", "30 ct", 349, 399, True,
     ["multivitamin", "wellness"],
     "Daily multivitamin and mineral tablets.",
     [], ["100% authentic, licensed seller", "Expiry: Nov 2027"], False, None),
    ("bandaid_01", "Adhesive Bandages", "20 pc", 45, 50, True,
     ["bandage", "first-aid"],
     "Waterproof adhesive bandages.",
     [], ["100% authentic, licensed seller", "Expiry: Mar 2029"], False, None),
    ("antiseptic_liquid_01", "Antiseptic Liquid", "100 ml", 65, 70, True,
     ["antiseptic", "first-aid"],
     "General purpose antiseptic liquid.",
     [], ["100% authentic, licensed seller", "Expiry: Feb 2028"], False, None),
    ("cough_syrup_01", "Cough Syrup", "100 ml", 110, 120, True,
     ["cough-syrup", "medicine"],
     "Herbal cough relief syrup.",
     [], ["100% authentic, licensed seller", "Expiry: Oct 2027"], False, None),
    ("hand_sanitizer_01", "Hand Sanitizer", "100 ml", 60, 65, True,
     ["sanitizer", "hygiene"],
     "70% alcohol-based hand sanitizer.",
     [], ["100% authentic, licensed seller", "Expiry: Jun 2027"], False, None),
    ("thermometer_01", "Digital Thermometer", "1 pc", 249, 279, True,
     ["thermometer", "device"],
     "Fast-read digital thermometer.",
     [], ["100% authentic, licensed seller", "1-yr warranty on device"], True, None),
    ("omega3_01", "Omega-3 Fish Oil Capsules", "60 ct", 449, 499, True,
     ["omega-3", "supplement"],
     "Fish oil capsules for heart and joint health.",
     [], ["100% authentic, licensed seller", "Expiry: Sep 2027"], False, None),
    ("electrolyte_powder_01", "Oral Electrolyte Powder Sachet", "1 pc", 15, 18, True,
     ["electrolyte", "hydration"],
     "WHO-formula oral rehydration sachet.",
     [], ["100% authentic, licensed seller", "Expiry: Aug 2027"], False, None),
],
"electronics": [
    ("charger_usbc_01", "20W USB-C Fast Charger", "1 pc", 799, 999, True,
     ["charger", "usb-c", "fast-charging"],
     "20W PD fast charger, works with most phones.",
     ["charging_cable_01"],
     ["Compatible with USB-C phones (check model)", "1-yr manufacturer warranty", "7-day easy return"], True, {"label": "20% OFF", "lowest_30d": True}),
    ("charging_cable_01", "USB-C to USB-C Cable", "1 m", 299, 349, True,
     ["cable", "usb-c"],
     "Braided USB-C to USB-C cable.",
     ["charger_usbc_01"],
     ["Compatible with USB-C devices", "6-month warranty", "7-day easy return"], False, None),
    ("earphones_01", "Wired Earphones with Mic", "1 pc", 399, 449, True,
     ["earphones", "audio"],
     "3.5mm wired earphones with inline mic.",
     [], ["Compatible with 3.5mm jack devices", "6-month warranty", "7-day easy return"], False, None),
    ("powerbank_01", "10000mAh Power Bank", "1 pc", 999, 1199, True,
     ["powerbank", "charging"],
     "Compact 10000mAh dual-output power bank.",
     ["charging_cable_01"],
     ["Compatible with USB-A and USB-C output", "1-yr manufacturer warranty", "7-day easy return"], True, None),
    ("bulb_smart_01", "Smart LED Bulb", "9 W", 449, 499, True,
     ["smart-bulb", "led", "home"],
     "Wi-Fi enabled dimmable smart bulb.",
     [], ["Compatible with 2.4GHz Wi-Fi", "1-yr manufacturer warranty", "7-day easy return"], False, None),
    ("extension_board_01", "4-Socket Extension Board", "1 pc", 349, 399, True,
     ["extension-board", "electrical"],
     "Surge-protected 4-socket extension board.",
     [], ["ISI-marked, surge protected", "1-yr manufacturer warranty", "7-day easy return"], False, None),
    ("batteries_aa_01", "AA Batteries", "4 pc", 149, 165, True,
     ["batteries", "aa"],
     "Long-life alkaline AA batteries.",
     [], ["Compatible with standard AA devices", "Expiry: 2030"], False, None),
    ("phone_stand_01", "Adjustable Phone Stand", "1 pc", 249, 279, True,
     ["phone-stand", "accessory"],
     "Foldable adjustable-angle phone stand.",
     [], ["Compatible with all phone sizes", "6-month warranty", "7-day easy return"], False, None),
    ("led_torch_01", "Rechargeable LED Torch", "1 pc", 349, 399, True,
     ["torch", "led", "emergency"],
     "USB-rechargeable high-beam LED torch.",
     [], ["Compatible with USB-A charging", "1-yr manufacturer warranty", "7-day easy return"], False, None),
    ("earbuds_case_01", "Wireless Earbuds Case", "1 pc", 1499, 1799, True,
     ["earbuds", "audio", "wireless"],
     "Bluetooth 5.3 wireless earbuds with charging case.",
     [], ["Compatible with Bluetooth 5.0+", "1-yr manufacturer warranty", "7-day easy return"], True, {"label": "17% OFF", "lowest_30d": False}),
],
"party_gifting": [
    ("party_supplies_set_01", "Birthday Party Supplies Set", "1 set", 399, 499, True,
     ["party", "birthday", "balloons", "streamers"],
     "Balloons, streamers and candles combo set for a birthday party.",
     ["candles_bday_01", "balloons_01", "confetti_01"],
     ["Set covers up to 10 guests"], True, {"label": "20% OFF", "lowest_30d": True}),
    ("candles_bday_01", "Birthday Candles", "10 pc", 49, 55, True,
     ["candles", "birthday"],
     "Number and stick birthday candles.",
     ["party_supplies_set_01"], ["Pack of 10"], False, None),
    ("balloons_01", "Latex Balloons", "50 pc", 99, 115, True,
     ["balloons", "party"],
     "Assorted-color latex balloons.",
     ["party_supplies_set_01"], ["Pack of 50"], False, None),
    ("gift_wrap_01", "Gift Wrapping Paper Roll", "1 roll", 79, 89, True,
     ["gift-wrap", "gifting"],
     "Glossy gift wrapping paper roll.",
     [], ["5m roll"], False, None),
    ("greeting_card_01", "Greeting Card", "1 pc", 59, 65, True,
     ["greeting-card", "gifting"],
     "Printed greeting card with envelope.",
     [], ["Single card with envelope"], False, None),
    ("party_hats_01", "Party Hats", "6 pc", 69, 79, True,
     ["party-hats", "birthday"],
     "Cone party hats, assorted colors.",
     ["party_supplies_set_01"], ["Pack of 6"], False, None),
    ("confetti_01", "Confetti Poppers", "2 pc", 89, 99, True,
     ["confetti", "party"],
     "Push-pop confetti poppers.",
     ["party_supplies_set_01"], ["Pack of 2"], False, None),
    ("chocolate_gift_box_01", "Assorted Chocolate Gift Box", "1 box", 349, 399, True,
     ["chocolate", "gifting"],
     "Assorted chocolate box for gifting.",
     [], ["Box of 16 pieces"], False, None),
    ("disposable_plates_01", "Disposable Paper Plates", "10 pc", 65, 72, True,
     ["plates", "party"],
     "Sturdy disposable paper plates.",
     ["party_supplies_set_01"], ["Pack of 10"], False, None),
    ("ribbon_roll_01", "Decorative Ribbon Roll", "1 roll", 49, 55, True,
     ["ribbon", "gifting"],
     "Satin decorative ribbon roll.",
     [], ["10m roll"], False, None),
],
"pet": [
    ("dog_food_01", "Dry Dog Food", "1 kg", 349, 389, True,
     ["dog-food", "pet"],
     "Balanced nutrition dry dog food.",
     [], ["Chicken-based protein, no fillers", "Expiry: Feb 2027"], False, None),
    ("cat_food_01", "Dry Cat Food", "1 kg", 399, 449, True,
     ["cat-food", "pet"],
     "Balanced nutrition dry cat food.",
     [], ["Fish-based protein, no fillers", "Expiry: Feb 2027"], False, None),
    ("pet_treats_01", "Pet Training Treats", "100 g", 149, 165, True,
     ["pet-treats", "training"],
     "Soft training treats for dogs.",
     [], ["Single-protein source", "Expiry: Nov 2026"], False, None),
    ("pet_shampoo_01", "Pet Shampoo", "200 ml", 249, 275, True,
     ["pet-shampoo", "grooming"],
     "Gentle pH-balanced pet shampoo.",
     [], ["Soap-free, tearless formula", "Expiry: Aug 2027"], False, None),
    ("litter_01", "Cat Litter", "2 kg", 299, 329, True,
     ["cat-litter", "pet"],
     "Clumping, odor-control cat litter.",
     [], ["Bentonite clay, low dust", "Expiry: N/A"], False, None),
    ("pet_toy_01", "Chew Toy for Dogs", "1 pc", 199, 225, True,
     ["pet-toy", "chew"],
     "Durable rubber chew toy.",
     [], ["Non-toxic rubber", "N/A"], False, None),
    ("pet_bowl_01", "Stainless Steel Pet Bowl", "1 pc", 249, 279, True,
     ["pet-bowl", "feeding"],
     "Anti-skid stainless steel pet bowl.",
     [], ["Food-grade steel", "N/A"], False, None),
    ("pet_leash_01", "Nylon Pet Leash", "1 pc", 299, 329, True,
     ["pet-leash", "walking"],
     "Strong nylon walking leash.",
     [], ["Rated up to 40kg pull", "N/A"], False, None),
    ("bird_seed_01", "Mixed Bird Seed", "500 g", 129, 145, True,
     ["bird-seed", "pet"],
     "Mixed seed blend for pet birds.",
     [], ["No artificial additives", "Expiry: Jan 2027"], False, None),
    ("fish_food_01", "Fish Feed Flakes", "50 g", 99, 110, True,
     ["fish-food", "pet"],
     "Nutrient-rich flake food for aquarium fish.",
     [], ["Balanced flake formula", "Expiry: Mar 2027"], False, None),
],
}

def build_catalog():
    categories = CATEGORIES
    trust_type_map = {c["category_id"]: c["trust_template"] for c in categories}
    skus = []
    for cat_id, items in SKUS_BY_CATEGORY.items():
        types = trust_type_map[cat_id]
        for (slug, name, unit, price, mrp, veg, tags, desc, complements, fact_labels, has_anchor, deal) in items:
            sku_id = f"sku_{slug}"
            trust_facts = []
            for i, t in enumerate(types):
                label = fact_labels[i] if i < len(fact_labels) else ""
                trust_facts.append({"fact_id": f"{slug}_{t[:4]}", "type": t, "label": label})
            sku = {
                "sku_id": sku_id,
                "name": name,
                "category_id": cat_id,
                "unit": unit,
                "price": price,
                "mrp": mrp,
                "veg": veg,
                "image": None,  # placeholder-tile rendering for all SKUs in this pass; see docs/implementation_plan.md Pre-Flight note
                "tags": tags,
                "description": desc,
                "trust_facts": trust_facts,
                "out_of_stock": False,
                "complements": [f"sku_{c}" for c in complements],
            }
            if has_anchor:
                # reference price ~8-20% above ours, deterministic from price
                sku["anchor_price"] = {"retailer": "BigBasket", "price": round(price * 1.12 / 5) * 5}
            if deal:
                sku["deal"] = deal
            skus.append(sku)
    return {"categories": categories, "skus": skus}


PERSONAS = {
    "priya": {
        "persona_id": "priya",
        "display_name": "Priya",
        "framing": "trust",
        "history_category_ids": ["staples", "dairy", "snacks", "household"],
        "order_again_sku_ids": [
            "sku_milk_01", "sku_atta_ww_01", "sku_toor_dal_01", "sku_curd_01",
            "sku_chips_classic_01", "sku_dishwash_liquid_01", "sku_rice_basmati_01",
            "sku_butter_01",
        ],
    },
    "ishaan": {
        "persona_id": "ishaan",
        "display_name": "Ishaan",
        "framing": "deal",
        "history_category_ids": [
            "staples", "snacks", "beverages", "dairy", "household",
            "beauty", "electronics", "party_gifting", "pet",
        ],
        "order_again_sku_ids": [
            "sku_cola_01", "sku_chips_classic_01", "sku_shampoo_01",
            "sku_powerbank_01", "sku_dog_food_01", "sku_coffee_instant_01",
        ],
    },
}


def main():
    os.makedirs(SHARED, exist_ok=True)
    catalog = build_catalog()
    assert len(catalog["skus"]) == 120, f"expected 120 SKUs, got {len(catalog['skus'])}"

    catalog_json = json.dumps(catalog, indent=2, ensure_ascii=False)
    with open(os.path.join(SHARED, "catalog.json"), "w", encoding="utf-8") as f:
        f.write(catalog_json)
    for pid, data in PERSONAS.items():
        with open(os.path.join(SHARED, f"{pid}.json"), "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    personas_json = json.dumps(PERSONAS, indent=2, ensure_ascii=False)
    personas_dest = os.path.join(ROOT, "frontend", "lib", "personas-data.json")
    os.makedirs(os.path.dirname(personas_dest), exist_ok=True)
    with open(personas_dest, "w", encoding="utf-8") as f:
        f.write(personas_json)

    # Sync copies — /shared/catalog.json is the source of truth, but the
    # backend (Render root=/backend) and frontend (Vercel root=/frontend)
    # each deploy from their own subtree, so both need their own copy.
    for dest in [
        os.path.join(ROOT, "backend", "data", "catalog.json"),
        os.path.join(ROOT, "frontend", "lib", "catalog-data.json"),
    ]:
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(dest, "w", encoding="utf-8") as f:
            f.write(catalog_json)

    print(f"Wrote {len(catalog['skus'])} SKUs across {len(catalog['categories'])} categories to {SHARED}")
    print("Synced copies to backend/data/catalog.json and frontend/lib/catalog-data.json")


if __name__ == "__main__":
    main()
